import { NextRequest } from 'next/server';
import { resources, resourceTypeLabels, getResourceLocale, type Resource } from '@/lib/data/resources';

function getResourceById(id: string): Resource | undefined {
  return resources.find((r) => r.id === id);
}

function generateHtmlDoc(resource: Resource, lang: 'en' | 'es'): string {
  const { title, description } = getResourceLocale(resource, lang);
  const isEs = lang === 'es';
  const typeLabel = resourceTypeLabels[resource.type];
  const now = new Date().toISOString().split('T')[0];

  const labels = isEs ? {
    type: 'Tipo',
    format: 'Formato',
    size: 'Tamaño',
    downloads: 'Descargas',
    description: 'Descripción',
    tags: 'Etiquetas',
    generated: 'Generado por Hustle Alliance',
    date: 'Fecha',
    about: 'Sobre este recurso',
    tableOfContents: 'Contenido',
    section1: '1. Resumen Ejecutivo',
    section1Text: 'Este recurso ha sido diseñado para emprendedores y fundadores que buscan construir negocios sostenibles. Contiene frameworks prácticos, plantillas accionables y guías paso a paso basadas en las mejores prácticas de la industria.',
    section2: '2. Cómo Usar Este Recurso',
    section2Text: 'Revisa cada sección en orden. Completa los ejercicios y plantillas incluidos. Adapta los frameworks a tu contexto específico. Comparte los resultados con tu equipo o mentor para obtener retroalimentación.',
    section3: '3. Próximos Pasos',
    section3Text: 'Después de completar este recurso, te recomendamos aplicarlo inmediatamente en tu negocio. La ejecución es lo que separa a los fundadores exitosos del resto.',
    disclaimer: 'Este recurso es parte de la biblioteca de Hustle Alliance. Distribución permitida solo para uso personal.',
  } : {
    type: 'Type',
    format: 'Format',
    size: 'Size',
    downloads: 'Downloads',
    description: 'Description',
    tags: 'Tags',
    generated: 'Generated by Hustle Alliance',
    date: 'Date',
    about: 'About This Resource',
    tableOfContents: 'Contents',
    section1: '1. Executive Summary',
    section1Text: 'This resource has been designed for entrepreneurs and founders building sustainable businesses. It contains practical frameworks, actionable templates, and step-by-step guides based on industry best practices.',
    section2: '2. How to Use This Resource',
    section2Text: 'Review each section in order. Complete the included exercises and templates. Adapt the frameworks to your specific context. Share results with your team or mentor for feedback.',
    section3: '3. Next Steps',
    section3Text: 'After completing this resource, apply it immediately in your business. Execution is what separates successful founders from the rest.',
    disclaimer: 'This resource is part of the Hustle Alliance library. Distribution permitted for personal use only.',
  };

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title} — Hustle Alliance</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.7;
    color: #1a1a2e;
    max-width: 800px;
    margin: 0 auto;
    padding: 60px 40px;
    background: #fff;
  }
  .header {
    border-bottom: 3px solid #ff3b30;
    padding-bottom: 30px;
    margin-bottom: 40px;
  }
  .badge {
    display: inline-block;
    background: #ff3b30;
    color: white;
    padding: 4px 14px;
    border-radius: 20px;
    font-size: 12px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1px;
    margin-bottom: 16px;
  }
  h1 {
    font-size: 32px;
    font-weight: 800;
    margin-bottom: 12px;
    line-height: 1.3;
  }
  .meta {
    color: #666;
    font-size: 14px;
    display: flex;
    gap: 24px;
    flex-wrap: wrap;
  }
  .meta span { display: flex; align-items: center; gap: 6px; }
  h2 {
    font-size: 20px;
    font-weight: 700;
    margin: 40px 0 16px;
    color: #1a1a2e;
  }
  p { margin-bottom: 16px; color: #333; }
  .content-section {
    background: #f8f9fa;
    border-radius: 12px;
    padding: 24px;
    margin-bottom: 24px;
  }
  .tags {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    margin-top: 16px;
  }
  .tag {
    background: #e9ecef;
    padding: 4px 12px;
    border-radius: 16px;
    font-size: 12px;
    color: #495057;
  }
  .footer {
    margin-top: 60px;
    padding-top: 20px;
    border-top: 1px solid #e9ecef;
    font-size: 12px;
    color: #999;
  }
  @media print {
    body { padding: 40px; }
  }
</style>
</head>
<body>
<div class="header">
  <div class="badge">${typeLabel}</div>
  <h1>${title}</h1>
  <div class="meta">
    <span>📄 ${labels.format}: ${resource.format}</span>
    <span>📦 ${labels.size}: ${resource.fileSize}</span>
    <span>⬇ ${resource.downloads.toLocaleString()} ${labels.downloads.toLowerCase()}</span>
    <span>📅 ${labels.date}: ${now}</span>
  </div>
</div>

<h2>${labels.about}</h2>
<p>${description}</p>

<div class="tags">
  ${resource.tags.map(tag => `<span class="tag">#${tag}</span>`).join('\n  ')}
</div>

<h2>${labels.tableOfContents}</h2>
<div class="content-section">
  <h3>${labels.section1}</h3>
  <p>${labels.section1Text}</p>
</div>
<div class="content-section">
  <h3>${labels.section2}</h3>
  <p>${labels.section2Text}</p>
</div>
<div class="content-section">
  <h3>${labels.section3}</h3>
  <p>${labels.section3Text}</p>
</div>

<div class="footer">
  <p>${labels.generated} · ${now}</p>
  <p>${labels.disclaimer}</p>
</div>
</body>
</html>`;
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const lang = (request.nextUrl.searchParams.get('lang') || 'en') as 'en' | 'es';
  const resource = getResourceById(id);

  if (!resource) {
    return new Response('Resource not found', { status: 404 });
  }

  const { title } = getResourceLocale(resource, lang);
  const html = generateHtmlDoc(resource, lang);
  const filename = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '') + '-' + lang + '.html';

  return new Response(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  });
}
