/**
 * Avatar URL normalization — maps known external avatar URLs (DiceBear, Unsplash)
 * to local SVG paths generated by scripts/generate-avatars.mjs.
 *
 * This ensures avatars work correctly whether the database has old or new URLs,
 * and provides a single place to manage avatar path resolution.
 */

// Maps DiceBear seed names to usernames (for local SVG path lookup)
const DICE_BEAR_TO_USERNAME: Record<string, string> = {
  'Admin': 'admin',
  'Marcus Chen': 'marcuschen',
  'Priya Patel': 'priyap',
  'Devon Mitchell': 'devonm',
  'Sarah Okonkwo': 'sarahk',
  'James Okafor': 'jameso',
  'Maya Rodriguez': 'maya',
  'Alex Kowalski': 'alexk',
  'Elena Kim': 'elenak',
  'David Liu': 'davidl',
  'Maria Torres': 'mariat',
  'Tom Baker': 'tomb',
  'Anna Williams': 'annaw',
  'Carlos Mendez': 'carlosm',
  'Fatima A': 'fatimaa',
  'Ryan Park': 'ryanp',
  'Yuki Tanaka': 'yukit',
  'Olivia Chen': 'oliviac',
  'Kwame Asante': 'kwamea',
  'Sofia Lindqvist': 'sofial',
  'Raj Patel': 'rajp',
  'Hannah Weiss': 'hannahw',
  'Omar Hassan': 'omarh',
  'Luna Park': 'lunap',
  'Viktor Petrov': 'viktorp',
  'Jiwoo Kim': 'jiwook',
  'Amelia Brooks': 'ameliab',
  'Kenji Nakamura': 'kenjin',
  'Zara Osei': 'zarao',
  'Nadia Petrova': 'nadiap',
  'Leo Fernandez': 'leof',
  'Anya Sharma': 'anyas',
  'Felix Bauer': 'felixb',
  'Priyanka Das': 'priyankad',
  'Max Andersson': 'maxa',
  'Isabelle Moreau': 'isabellem',
  'Cam Nguyen': 'camn',
  'Grace Okafor': 'graceo',
  'Dmitri Volkov': 'dmitriv',
  'Mei Lin': 'meil',
  'Hasan Yilmaz': 'hasany',
  'Chiara Rossi': 'chiarar',
  'Tong Wei': 'tongw',
  'Aspen Wright': 'aspenw',
  'Karim Benali': 'karimb',
  'Mira Joshi': 'miraj',
  'Erik Johansson': 'erikj',
  'Tosin Adebayo': 'tosina',
  "Sam O'Brien": 'samo',
  'Lucia Vargas': 'luciav',
  'Arjun Mehta': 'arjunm',
  'Leila Haddad': 'leilah',
  'Haruki Sato': 'harukis',
  'Noor Ali': 'noora',
  'Mateo Garcia': 'mateog',
  'Lina Bergstrom': 'linab',
  'Lina Bergström': 'linab',
  'Tyrone Jackson': 'tyronej',
  'Sakura Yamamoto': 'sakuray',
  'Ibrahim Khoury': 'ibrahimk',
  'Chantal Mukamana': 'chantalm',
  'Jonas Mueller': 'jonasm',
  'Aisha Bello': 'aishab',
  'Taylor Reed': 'taylorr',
  'Jordan Blake': 'jordanb',
  'Riley Morgan': 'rileym',
  'Casey Kim': 'caseyk',
  'Drew Patterson': 'drewp',
  'Avery Santos': 'averys',
  'Quinn Foster': 'quinnf',
  'Morgan Yu': 'morgany',
  'Founder': 'alexk',
  'Sarah Kim': 'sarahk',
};

// Maps Unsplash photo IDs to usernames (instructors)
const UNSPLASH_TO_USERNAME: Record<string, string> = {
  'photo-1507003211169-0a1dd7228f2d': 'marcuschen',
  'photo-1494790108377-be9c29b29330': 'priyap',
  'photo-1506794778202-cad84cf45f1d': 'devonm',
  'photo-1573497019940-1c28c88b4f3e': 'sarahk',
};

/** URL patterns that indicate an external avatar source */
const EXTERNAL_PATTERNS = ['api.dicebear.com', 'images.unsplash.com'];

/**
 * Normalizes an avatar URL, mapping known external URLs to local SVG paths.
 * Returns the original URL unchanged if it's already a local path or unknown.
 */
export function normalizeAvatarUrl(url: string | null): string | null {
  if (!url) return null;
  if (url.startsWith('/')) return url; // already local

  const isExternal = EXTERNAL_PATTERNS.some((p) => url.includes(p));
  if (!isExternal) return url;

  // Try Unsplash mapping first
  for (const [photoId, username] of Object.entries(UNSPLASH_TO_USERNAME)) {
    if (url.includes(photoId)) return `/images/avatars/${username}.svg`;
  }

  // Try DiceBear mapping: extract seed from URL
  // Handle both %20 and + space encoding in query strings
  const seedMatch = url.match(/[?&]seed=([^&]+)/);
  if (seedMatch) {
    const rawSeed = seedMatch[1];
    const seed = decodeURIComponent(rawSeed.replace(/\+/g, ' '));
    const username = DICE_BEAR_TO_USERNAME[seed];
    if (username) return `/images/avatars/${username}.svg`;
  }

  // Unknown external URL — return as-is (it may still work)
  return url;
}
